name: Deployment
on:
  push:
    branches: [devedelop, releases/**, master]
  workflow_dispatch:
env:
  LOCAL_REUSEABLE_WORKFLOW_REF: dev
jobs:
  pipeline:
    uses: sfier-playground/github-action-share-template/.github/workflows/go_deliver.yml@$LOCAL_REUSEABLE_WORKFLOW_REF
    with:
      service-name: device-interactions
    secrets: inherit
