name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop, master]
jobs:
  ci:
    uses: sfier-playground/github-action-share-template/.github/workflows/go_ci.yml@master
