name: CI
on:
  pull_request:
    types: [opened, reopened]
jobs:
  go-ci:
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: $GITHUB_TOKEN

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
