name: Deployment
on:
  push:
    branches: [dev, stage, master]
  workflow_dispatch:
jobs:
  pipeline:
    uses: sfier-playground/github-action-share-template/.github/workflows/go_workflow.yml@master
    secrets:
      GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
 ## trigger pipline
