name: Deployment
on:
  push:
    branches: [develop, stage, master]
  workflow_dispatch:
jobs:
  pipeline:
    uses: sfier-playground/github-action-share-template/.github/workflows/go_workflow.yml@master
    environment: dev
    with:
      service-name: ${{vars.SERVICE_NAME}}
      ref: ${{ github.sha }}
    secrets: inherit
